#include<iostream>
using namespace std;

int main(){
    cout << "Hello World" << "\n"; // "\n" is faster than endl
    //Output in C++ -> cout <<.....
    cout << "Hello World" << endl; // Due to "endl" there is no trailing character
    cout << "Hello World"; // Here there is no "endl" so you see a trailing character "%"
    return 0;
    // If you do not use "using namespace std;" then each time you write cout or anything you
    // need to write like this "std::cout << "Hello World" "
}
/*
FULL PROCESS:-
1. iostream Header and Namespace
The iostream header file in C++ declares essential input-output functionalities, like cin, cout, endl, and other related functions.

These functions are declared inside the std namespace. The namespace helps to avoid naming conflicts in larger programs. So, when you write cout, it actually refers to std::cout, which is why you need to either use the std:: prefix or write using namespace std; to avoid repeating std:: every time.

2. Compiling
The compiler checks the source code for syntax errors and logical issues. It converts your human-readable code into machine-readable object code (intermediate code).

However, the compiler doesn't know the exact implementation of functions like cout—it just knows they exist in iostream.

3. Linking
After the code is compiled, the linker comes into play. The linker combines your compiled code with external libraries (like the C++ Standard Library, which contains the actual definition of cout).

If the linker cannot find the necessary definitions (for example, if you miss including iostream), you'll get a linking error.

4. Runtime
Once the code has been successfully compiled and linked, your program enters the runtime phase. This is where the program actually executes.

Functions like cout (which outputs data) or cin (which takes user input) work during runtime when the program is running.

# Example Process Flow:
Write Code: You write #include <iostream>, using namespace std;, and use cout in your code.

Compile: The compiler checks for syntax errors and converts the code into object code, but it doesn't know how cout works yet.

Link: The linker combines your object code with the necessary libraries (like iostream) and resolves external symbols like cout.

Run: The program runs, and during runtime, cout outputs data to the screen.

# Key Concepts Recap:
iostream: A header file that declares input/output functions.

Namespace std: Organizes standard functions like cout and cin to avoid naming conflicts.

Compiler: Translates the code into machine-readable form.

Linker: Combines the compiled code with external libraries (like iostream) and resolves symbols.

Runtime: The phase when the program executes, and functions like cout and cin actually perform actions.



In C++, when you write code using iostream, you're including a header file that declares essential input-output functionalities like cin, cout, and endl. 
The iostream header doesn't directly define how cout works; it merely declares that cout exists within the std namespace. The namespace std is a way of organizing code and functions in C++ to prevent name conflicts. 
Without the std:: prefix or a using namespace std; declaration, you must explicitly reference the cout function as std::cout because it's defined in the std namespace.

Now, when you compile C++ code, the compiler checks for syntax and logical errors. It converts your human-readable code into machine code that a computer can execute. 
However, compiling doesn’t bring in the actual implementation of cout; that comes during linking. The linker takes all the compiled code and links it with external libraries (like the C++ Standard Library that provides cout and other functions). 
This is where the actual code for cout and other functionalities gets connected to your program. If the linker can't find the implementation of something you referenced (like cout from iostream), you'll get a linking error.

After the code is compiled and linked, the program enters the runtime phase, where it actually runs. 
At this point, the computer executes the machine code generated by the compiler and linked libraries. 
During runtime, things like user input (cin) and output (cout) occur, meaning the program interacts with the user.

In short, iostream and namespace std help organize and access functionality like cout. 
Compilation prepares the code, linking connects it to external libraries, and runtime is when the actual execution happens. 
Without proper linking, even though the compiler generates code, the program cannot run successfully because the necessary library implementations are missing.

*/